version: '1.0.0'

x-common-variables: &common-variables
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASSWORD

services:
  db:
    # This image is not custom and can be found on docker hub so don't need to push
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api-server/db-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_HOST: $MYSQL_HOST

  nginx:
    # This image is not custom and can be found on docker hub so don't need to push
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8008:80"

  api:
    build:
      context: ./api-server
      target: dev
    image: jainalertsummer2024/api:7800_sanket
    #image: jainalertsummer2024/<YOUR_PROJECT>:<YOUR_GROUP_ID>_<NAME>
    depends_on:
      - db
    volumes:
      - ./api-server:/src
      - /src/node_modules
    command: npm run start:dev
    ports:
      - $API_PORT:$API_PORT
    environment:
      <<: *common-variables
      PORT: $API_PORT
      NODE_ENV: development

  ui:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./blog-ui
    image: jainalertsummer2024/blog-ui:7800_sanket
    #image: jainalertsummer2024/<YOUR_PROJECT>:<YOUR_GROUP_ID>_<NAME>
    volumes:
      - ./blog-ui:/src
      - /src/node_modules
    ports:
      - $CLIENT_PORT:$CLIENT_PORT

  adminer:
    image: jainalertsummer2024/adminer:7800_sanket
    #image: jainalertsummer2024/<YOUR_PROJECT>:<YOUR_GROUP_ID>_<NAME>
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql_data:
