version: '3.8'

services:
  central_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
